### ISSUE TITLE
Sample documentation for styling

### ISSUE THREAD

**Issue by papylhomme** [sgratzl/chartjs-chart-error-bars#7]
Hello,

could you add a styling example in the documentation ? I'm not fluent using ChartJS and I didn't manage to style error bars, where should I put the configuration options ?

**Comment by sgratzl** [comment]
anything specific that you wanna achieve? Then I could create a code pen for it

**Comment by papylhomme** [comment]
Nothing fancy, the interface `IErrorBarStyling` is self explanatory but I was looking for a way to apply the options, something like what they did for the [datalabels plugins](https://chartjs-plugin-datalabels.netlify.com/guide/getting-started.html#configuration).

Specifically I've tried this with variation of the 'errorbars' key (camel cased, with the '-', 'chart-error-bar', ...)

    const chart = new Chart(ctx, {
      options: {
          plugins: {
              errorbars: {
                  errorBarColor: '#36A2EB'
              }
          }
      },
      // ...
    }

**Comment by sgratzl** [comment]
since they are regular graphical elements there are two locations where they can be configured. 

1. similar to configure the backgroundColor of the rect: once per dataset (next to the `data: ...` )
 2. in the default options of the elements: `options: { elements: { rectangleWithErrorBar: { ... }}}`. 

see also https://codepen.io/sgratzl/pen/ExVYQXB.

**Comment by papylhomme** [comment]
Thanks, I didn't understood it that way. For the record, styling error bars on a scatter:

        elements: {
          pointWithErrorBar: {
            errorBarWhiskerSize: 10
          },
          point: {
            radius: 5
          }
        },
